### ISSUE TITLE
Cannot redeclare EDI\\Reader::getParsedFile() in /var/www/edifact/vendor/sabas/edifact/src/EDI/Reader.php on line 65

### ISSUE THREAD

**Issue by kikiazerty** [sabas/edifact#9]
Hi

Cannot redeclare EDI\\Reader::getParsedFile() in /var/www/project/vendor/sabas/edifact/src/EDI/Reader.php on line 65

function getParsedFile() id declared twice at line 50 and 65
after remove this twice decalaration

I have PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/project/vendor/sabas/edifact/src/EDI/Reader.php on line 170

**Comment by sabas** [comment]
@kikiazerty could you tell me which is the line 170? I am assuming you say 170 after removing the declaration so it could be this line https://github.com/sabas/edifact/blob/master/src/EDI/Reader.php#L174

It's possible you're using a version of PHP less than 5.4? Because it could be the square brackets notation...

**Comment by kikiazerty** [comment]
Hi Sabas, thanks you,
Correct, I was using a version less than 5.4 and i can't use php shorthand array, I have installed php 5.4 and all is ok now

Regards
